# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  tags:
    include:
      - v*
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreInstaller@1
  inputs:
    version: '3.0.100-preview9-014004'

- task: CopyFiles@2
  inputs:
    sourceFolder: VncDotnet
    targetFolder: '$(Build.ArtifactStagingDirectory)/src/VncDotnet'
    contents: |
      **\*.cs
      **\*.csproj

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    nobuild: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    searchPatternPack: '**/VncDotnet.csproj'
    nobuild: true

- powershell: $foo = ls $(Build.ArtifactStagingDirectory) | where { $_.Name.endswith(".snupkg") } | select -ExpandProperty Name; echo "##vso[task.setvariable variable=filename;isOutput=true]$foo"
  name: SymbolsPackage

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/src'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(SymbolsPackage.filename)'
    replaceExistingArchive: false
    verbose: true

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/$(SymbolsPackage.filename)'
    destinationFolder: '$(Build.ArtifactStagingDirectory)/final_snupkg'

- script: tree /F $(Build.ArtifactStagingDirectory)

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget.org'
